juego:
    path:     /
    defaults: { _controller: "TopGamesBundle:Juego:index" }

juego_show:
    path:     /{id}/show
    defaults: { _controller: "TopGamesBundle:Juego:show" }

juego_new:
    path:     /new
    defaults: { _controller: "TopGamesBundle:Juego:new" }

juego_create:
    path:     /create
    defaults: { _controller: "TopGamesBundle:Juego:create" }
    methods:  POST

juego_edit:
    path:     /{id}/edit
    defaults: { _controller: "TopGamesBundle:Juego:edit" }

juego_update:
    path:     /{id}/update
    defaults: { _controller: "TopGamesBundle:Juego:update" }
    methods:  [POST, PUT]
    
juego_plataformas:
    path:     /{id}/juego-plataformas
    defaults: { _controller: "TopGamesBundle:Juego:juegoPlataformas" }

juego_plataformas_nuevo: 
    path:     /addPlataforma/{idJuego}/{idPlataforma}
    defaults: { _controller: "TopGamesBundle:Juego:plataforma_save" }
    
juego_plataformas_borrar: 
    path:     /removePlataforma/{idJuego}/{idPlataforma}
    defaults: { _controller: "TopGamesBundle:Juego:plataforma_delete" }
    
    
juego_delete:
    path:     /{id}/delete
    defaults: { _controller: "TopGamesBundle:Juego:delete" }
    methods:  [POST, DELETE]
    
juego_add_to_list:
    path:     /addToList
    defaults: {_controller: TopGamesBundle:Juego:addToList}
    methods:  [POST]