security:
        
    encoders:
        JorgeLillo\TopGamesBundle\Entity\Usuario:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: TopGamesBundle:Usuario, property: username}

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        area_segura:
            pattern:   ^/
            anonymous: ~
            form_login:
                csrf_provider: form.csrf_provider
                login_path: login
                check_path: login_check
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
