JorgeLillo\TopGamesBundle\Entity\Usuario:
    type: entity
    table: usuario
    uniqueConstraints:
        username_UNIQUE:
            columns:
                - username
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 16
            fixed: false
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
        isAdmin:
            type: boolean
            nullable: true
            unsigned: false
            default: false
            column: esAdmin
        email:
            type: string
            nullable: true
            length: 255
            fixed: false
        createTime:
            type: datetime
            nullable: true
            default: CURRENT_TIMESTAMP
            column: create_time
        isActive:
            type: boolean
            nullable: true
            unsigned: false
            default: true
            column: esActivo
    lifecycleCallbacks: {  }
